name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        AZURE_SPEECH_RESOURCE_KEY: ${{ secrets.AZURE_SPEECH_RESOURCE_KEY }} 
        AZURE_SPEECH_REGION: ${{ secrets.AZURE_SPEECH_REGION }} 
      run: |
        timeout --signal=INT 30 pytest -v --full-trace --color=yes --code-highlight=yes --debug=pytest-debug.log
